In [1]:
# imports and setup
import pandas as pd
import numpy as np
import sklearn
import sklearn2pmml
import sklearn_pandas
from sklearn import svm
from sklearn2pmml.pipeline import PMMLPipeline
from sklearn2pmml import sklearn2pmml

import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (15, 9)
plt.style.use('ggplot')

In [2]:
df = pd.read_csv("test.csv")
df

,item_id,olive oil,salt,garlic,lemon juice,garlic cloves,salt and pepper,kosher salt,onion,anchovy,...,herbes de provence,deep dish pie crust,yellow tomato,winter squash,wasabi peas,butter beans,pork chops,orange roughy,watermelon,Unnamed: 1001
0,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,NaN
1,2,0,1,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,NaN
2,3,0,0,1,0,1,0,0,1,0,...,0,0,0,0,0,1,0,0,0,NaN
3,4,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,NaN
4,5,0,1,1,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1441,1442,1,1,0,0,0,0,1,1,0,...,0,0,0,0,0,1,0,0,0,NaN
1442,1443,0,1,0,0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,NaN
1443,1444,1,1,0,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1444,1445,1,1,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1445,1446,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,NaN

In [3]:
columns = ['item_id']
df_y = pd.DataFrame(df, columns=columns)
df_y

      item_id
0           1
1           2
2           3
3           4
4           5
...       ...
1441     1442
1442     1443
1443     1444
1444     1445
1445     1446

[1446 rows x 1 columns]

In [4]:
df_X = df.drop(df.columns[0], axis='columns')
df_X = df_X.drop(df_X.columns[-1], axis='columns')
# X_train=X_train.drop(X_train.columns[x], axis='columns')
df_X

,olive oil,salt,garlic,lemon juice,garlic cloves,salt and pepper,kosher salt,onion,anchovy,black pepper,...,anchovies in olive oil,herbes de provence,deep dish pie crust,yellow tomato,winter squash,wasabi peas,butter beans,pork chops,orange roughy,watermelon
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,1,1,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1441,1,1,0,0,0,0,1,1,0,1,...,1,0,0,0,0,0,1,0,0,0
1442,0,1,0,0,0,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1443,1,1,0,1,0,1,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1444,1,1,1,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1445,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# model = svm.SVC(kernel='rbf', C=20)
# model.fit(df_X, df_y)

In [6]:
# fridge1 = [[1., 0., 0., 0., 1., 0., 0., 1., 0., 0.]]
# model.predict(fridge1)

In [7]:
# prop = model.decision_function(fridge1) 
# print(prop)

In [8]:
# best_n = np.argsort(prop, axis=1)[:,-10:]
# print(best_n)

In [9]:
model = svm.SVC(kernel='rbf', C=20)

In [10]:
pipeline = PMMLPipeline([
    ("classifier", model)
])

/usr/local/lib/python3.7/site-packages/sklearn/base.py:213: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)

In [11]:
pipeline.fit(df_X, df_y.values.ravel())

PMMLPipeline(steps=[('classifier', SVC(C=20))])

In [12]:
sklearn2pmml(pipeline, "svm_test.pmml",with_repr= True)